"""External Partner routes — public lookup, internal validation, SU admin CRUD.

Plan: ../../plans/external_partners_plan.md §4-§6.

Three groups of endpoints sharing the ``ExternalPartner`` model:

  Public  (no auth)         GET    /api/public/partner/<guid>
  Internal (service-key)    POST   /api/internal/partner/<guid>/validate
  Admin   (SU bearer token) GET    /api/admin/partners
                            POST   /api/admin/partners
                            GET    /api/admin/partners/<guid>
                            PATCH  /api/admin/partners/<guid>
                            POST   /api/admin/partners/<guid>/rotate
                            POST   /api/admin/partners/<guid>/suspend
                            POST   /api/admin/partners/<guid>/reactivate
                            POST   /api/admin/partners/<guid>/revoke
                            GET    /api/admin/partners/<guid>/audit

Credentials are generated by the server at create / rotate time, hashed
with the same scheme as user passwords, and shown to the SU exactly once
(in the response body of POST /partners or POST /partners/<guid>/rotate).
"""
import secrets
from datetime import datetime, timezone

from flask import Blueprint, request, jsonify, g

from src.db import get_db
from src.middleware.auth_middleware import (
    require_auth, require_su, require_service_key,
)
from src.models.external_partner import ExternalPartner, ExternalPartnerAudit
from src.services.auth_service import hash_password, verify_password
from src.services.audit_log import audit


partners_bp = Blueprint('partners', __name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Closed-set scope catalogue (plan §9 q2: SU decision = constrained list).
# Adding a new scope = code change reviewed in PR.
SCOPE_CATALOGUE = [
    'fhir.observation.read',
    'fhir.observation.write',
    'fhir.patient.read',
    'fhir.patient.write',
    'fhir.condition.read',
    'fhir.encounter.read',
    'fhir.questionnaireresponse.read',
    'fhir.questionnaireresponse.write',
    'cohort.read',
    'cohort.export',
]

# Names of internal services a partner may be allowed to call. Mirrors the
# Service Registry on the SSO landing.
KNOWN_SERVICES = [
    'cdr.pdhc',
    'gateway.pdhc',
    'dashboard.pdhc',
    'plan.pdhc',
    'contract.pdhc',
    'request.pdhc',
    'rosetta.pdhc',
    'ips.pdhc',
    '1177.pdhc',
    'cgm.pdhc',
    'forms.pdhc',
    'provider1.pdhc',
]


def _generate_secret() -> str:
    """43-char URL-safe token. Same shape as service keys already in use."""
    return secrets.token_urlsafe(32)


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _record_audit(session, partner: ExternalPartner, event: str,
                  before: dict | None, after: dict | None,
                  actor_user_guid: str | None) -> None:
    entry = ExternalPartnerAudit(
        partner_guid=partner.guid,
        actor_user_guid=actor_user_guid,
        event=event,
        before_json=before,
        after_json=after,
        at=_now(),
    )
    session.add(entry)


def _validate_payload(data: dict, *, creating: bool) -> tuple[dict | None, str | None]:
    """Validate user-supplied fields. Returns (cleaned, None) or (None, error)."""
    if not isinstance(data, dict):
        return None, "request body must be a JSON object"

    cleaned = {}

    if creating:
        for required in ('display_name', 'country_code', 'contact_email', 'auth_kind'):
            if not data.get(required):
                return None, f"missing required field: {required}"

    for f in ('display_name', 'org_number', 'description', 'contact_name',
              'contact_email', 'contact_phone'):
        if f in data:
            v = data[f]
            if v is not None and not isinstance(v, str):
                return None, f"{f} must be a string"
            cleaned[f] = v

    if 'country_code' in data:
        cc = data['country_code']
        if not isinstance(cc, str) or len(cc) != 2:
            return None, "country_code must be a 2-letter ISO code"
        cleaned['country_code'] = cc.upper()

    if 'auth_kind' in data:
        ak = data['auth_kind']
        if ak not in ('oauth_client', 'api_key', 'none'):
            return None, "auth_kind must be one of oauth_client, api_key, none"
        cleaned['auth_kind'] = ak

    for list_field in ('allowed_scopes', 'allowed_services', 'allowed_org_guids'):
        if list_field in data:
            v = data[list_field]
            if v is None and list_field == 'allowed_org_guids':
                cleaned[list_field] = None
                continue
            if not isinstance(v, list) or any(not isinstance(x, str) for x in v):
                return None, f"{list_field} must be a list of strings"
            cleaned[list_field] = v

    if cleaned.get('allowed_scopes'):
        bad = [s for s in cleaned['allowed_scopes'] if s not in SCOPE_CATALOGUE]
        if bad:
            return None, f"unknown scope(s): {bad}; see SCOPE_CATALOGUE"

    if cleaned.get('allowed_services'):
        bad = [s for s in cleaned['allowed_services'] if s not in KNOWN_SERVICES]
        if bad:
            return None, f"unknown service(s): {bad}"

    if 'expires_at' in data:
        v = data['expires_at']
        if v is None:
            cleaned['expires_at'] = None
        else:
            try:
                cleaned['expires_at'] = datetime.fromisoformat(v.replace('Z', '+00:00'))
            except (ValueError, AttributeError):
                return None, "expires_at must be ISO-8601 or null"

    return cleaned, None


# ---------------------------------------------------------------------------
# Public — partner lookup (used by contract.pdhc and any UI rendering Contracts)
# ---------------------------------------------------------------------------

@partners_bp.route('/api/public/partner/<guid>', methods=['GET'])
def public_partner(guid: str):
    """Sparse partner record — display_name + country + status. No contacts,
    no scopes, no auth material."""
    session = get_db()
    p = session.query(ExternalPartner).filter_by(guid=guid).first()
    if p is None:
        return jsonify({'error': 'not_found'}), 404
    return jsonify(p.public_dict()), 200


# ---------------------------------------------------------------------------
# Internal — service-to-service partner credential validation
# ---------------------------------------------------------------------------

@partners_bp.route('/api/internal/partner/<guid>/validate', methods=['POST'])
@require_service_key
def validate_partner(guid: str):
    """Verify a partner credential and return the access blob.

    Body: ``{"secret": "<api_key_or_client_secret>"}``

    Returns:
      200 with ``{access_blob: {...}}`` if valid + active + unexpired
      401 if invalid
      403 if suspended / revoked / expired
      404 if no such partner
    """
    body = request.get_json(silent=True) or {}
    secret = body.get('secret', '')
    if not secret:
        return jsonify({'error': 'missing_secret'}), 400

    session = get_db()
    p = session.query(ExternalPartner).filter_by(guid=guid).first()
    if p is None:
        return jsonify({'error': 'not_found'}), 404

    if p.status != 'active':
        return jsonify({'error': 'forbidden', 'reason': p.status}), 403

    if p.expires_at and p.expires_at < _now():
        return jsonify({'error': 'forbidden', 'reason': 'expired'}), 403

    stored = p.client_secret_hash if p.auth_kind == 'oauth_client' else p.api_key_hash
    if not stored or not verify_password(secret, stored):
        return jsonify({'error': 'unauthorized'}), 401

    blob = {
        'user_type': 'partner',
        'partner_guid': p.guid,
        'display_name': p.display_name,
        'allowed_scopes': p.allowed_scopes or [],
        'allowed_services': p.allowed_services or [],
        'allowed_org_guids': p.allowed_org_guids,
        'is_su_admin': False,
        'organization_ids': p.allowed_org_guids or [],
    }
    return jsonify({'access_blob': blob}), 200


# ---------------------------------------------------------------------------
# Admin — SU CRUD
# ---------------------------------------------------------------------------

@partners_bp.route('/api/admin/partners', methods=['GET'])
@require_auth
@require_su
def admin_list_partners():
    session = get_db()
    rows = session.query(ExternalPartner).order_by(ExternalPartner.created_at.desc()).all()
    return jsonify({'partners': [r.admin_dict() for r in rows]}), 200


@partners_bp.route('/api/admin/partners', methods=['POST'])
@require_auth
@require_su
def admin_create_partner():
    """Register a new partner. Generates the credential server-side and
    returns the cleartext exactly once — the SU must copy it now or rotate."""
    cleaned, err = _validate_payload(request.get_json(silent=True) or {}, creating=True)
    if err:
        return jsonify({'error': 'invalid', 'message': err}), 400

    session = get_db()
    p = ExternalPartner(
        display_name=cleaned['display_name'],
        org_number=cleaned.get('org_number'),
        country_code=cleaned['country_code'],
        description=cleaned.get('description'),
        contact_name=cleaned.get('contact_name'),
        contact_email=cleaned['contact_email'],
        contact_phone=cleaned.get('contact_phone'),
        auth_kind=cleaned['auth_kind'],
        allowed_scopes=cleaned.get('allowed_scopes', []),
        allowed_services=cleaned.get('allowed_services', []),
        allowed_org_guids=cleaned.get('allowed_org_guids'),
        expires_at=cleaned.get('expires_at'),
        created_by_user_guid=g.current_user.guid,
    )

    cleartext = None
    if p.auth_kind == 'api_key':
        cleartext = _generate_secret()
        p.api_key_hash = hash_password(cleartext)
        p.last_rotated_at = _now()
    elif p.auth_kind == 'oauth_client':
        p.client_id = secrets.token_urlsafe(16)
        cleartext = _generate_secret()
        p.client_secret_hash = hash_password(cleartext)
        p.last_rotated_at = _now()

    session.add(p)
    session.flush()  # so p.guid is populated for audit
    _record_audit(session, p, 'created', None, p.admin_dict(), g.current_user.guid)
    session.commit()

    audit('partner.created', user_guid=g.current_user.guid,
          detail={'partner_guid': p.guid, 'display_name': p.display_name})

    response = p.admin_dict()
    if cleartext:
        response['secret_cleartext'] = cleartext
        response['secret_warning'] = (
            "This secret will not be shown again. Copy it now and deliver "
            "it to the partner via a secure channel."
        )
    return jsonify(response), 201


@partners_bp.route('/api/admin/partners/<guid>', methods=['GET'])
@require_auth
@require_su
def admin_get_partner(guid: str):
    session = get_db()
    p = session.query(ExternalPartner).filter_by(guid=guid).first()
    if p is None:
        return jsonify({'error': 'not_found'}), 404
    return jsonify(p.admin_dict()), 200


@partners_bp.route('/api/admin/partners/<guid>', methods=['PATCH'])
@require_auth
@require_su
def admin_edit_partner(guid: str):
    """Edit mutable fields. Cannot change country_code, org_number,
    auth_kind — those changes require revoke + re-register (plan §5.3)."""
    cleaned, err = _validate_payload(request.get_json(silent=True) or {}, creating=False)
    if err:
        return jsonify({'error': 'invalid', 'message': err}), 400

    immutable_attempted = [k for k in ('country_code', 'org_number', 'auth_kind')
                          if k in cleaned]
    if immutable_attempted:
        return jsonify({
            'error': 'invalid',
            'message': f"cannot change {immutable_attempted} after creation; "
                       f"revoke and re-register",
        }), 400

    session = get_db()
    p = session.query(ExternalPartner).filter_by(guid=guid).first()
    if p is None:
        return jsonify({'error': 'not_found'}), 404

    before = p.admin_dict()
    for k, v in cleaned.items():
        setattr(p, k, v)
    p.updated_at = _now()
    _record_audit(session, p, 'edited', before, p.admin_dict(), g.current_user.guid)
    session.commit()
    audit('partner.edited', user_guid=g.current_user.guid,
          detail={'partner_guid': p.guid})
    return jsonify(p.admin_dict()), 200


@partners_bp.route('/api/admin/partners/<guid>/rotate', methods=['POST'])
@require_auth
@require_su
def admin_rotate_credential(guid: str):
    """Rotate the partner's credential. Old secret stops working immediately.
    New secret returned once."""
    session = get_db()
    p = session.query(ExternalPartner).filter_by(guid=guid).first()
    if p is None:
        return jsonify({'error': 'not_found'}), 404
    if p.auth_kind == 'none':
        return jsonify({'error': 'invalid', 'message': 'partner has no credential'}), 400

    before = p.admin_dict()
    cleartext = _generate_secret()
    if p.auth_kind == 'api_key':
        p.api_key_hash = hash_password(cleartext)
    else:
        p.client_secret_hash = hash_password(cleartext)
    p.last_rotated_at = _now()
    p.updated_at = p.last_rotated_at
    _record_audit(session, p, 'rotated', before, p.admin_dict(), g.current_user.guid)
    session.commit()
    audit('partner.rotated', user_guid=g.current_user.guid,
          detail={'partner_guid': p.guid})

    return jsonify({
        **p.admin_dict(),
        'secret_cleartext': cleartext,
        'secret_warning': (
            "Old credential is now invalid. New secret will not be shown "
            "again — copy it now and deliver to the partner securely."
        ),
    }), 200


@partners_bp.route('/api/admin/partners/<guid>/suspend', methods=['POST'])
@require_auth
@require_su
def admin_suspend(guid: str):
    session = get_db()
    p = session.query(ExternalPartner).filter_by(guid=guid).first()
    if p is None:
        return jsonify({'error': 'not_found'}), 404
    if p.status == 'revoked':
        return jsonify({'error': 'invalid', 'message': 'already revoked'}), 400
    before = p.admin_dict()
    p.status = 'suspended'
    p.updated_at = _now()
    _record_audit(session, p, 'suspended', before, p.admin_dict(), g.current_user.guid)
    session.commit()
    audit('partner.suspended', user_guid=g.current_user.guid,
          detail={'partner_guid': p.guid})
    return jsonify(p.admin_dict()), 200


@partners_bp.route('/api/admin/partners/<guid>/reactivate', methods=['POST'])
@require_auth
@require_su
def admin_reactivate(guid: str):
    session = get_db()
    p = session.query(ExternalPartner).filter_by(guid=guid).first()
    if p is None:
        return jsonify({'error': 'not_found'}), 404
    if p.status != 'suspended':
        return jsonify({'error': 'invalid', 'message': f'not suspended (status={p.status})'}), 400
    before = p.admin_dict()
    p.status = 'active'
    p.updated_at = _now()
    _record_audit(session, p, 'reactivated', before, p.admin_dict(), g.current_user.guid)
    session.commit()
    audit('partner.reactivated', user_guid=g.current_user.guid,
          detail={'partner_guid': p.guid})
    return jsonify(p.admin_dict()), 200


@partners_bp.route('/api/admin/partners/<guid>/revoke', methods=['POST'])
@require_auth
@require_su
def admin_revoke(guid: str):
    """Irreversible at the SSO layer — registering again requires a new GUID."""
    body = request.get_json(silent=True) or {}
    reason = body.get('reason') or ''
    session = get_db()
    p = session.query(ExternalPartner).filter_by(guid=guid).first()
    if p is None:
        return jsonify({'error': 'not_found'}), 404
    if p.status == 'revoked':
        return jsonify({'error': 'invalid', 'message': 'already revoked'}), 400
    before = p.admin_dict()
    p.status = 'revoked'
    p.revoked_at = _now()
    p.revoke_reason = reason
    p.updated_at = p.revoked_at
    _record_audit(session, p, 'revoked', before, p.admin_dict(), g.current_user.guid)
    session.commit()
    audit('partner.revoked', user_guid=g.current_user.guid,
          detail={'partner_guid': p.guid, 'reason': reason})
    return jsonify(p.admin_dict()), 200


@partners_bp.route('/api/admin/partners/<guid>/audit', methods=['GET'])
@require_auth
@require_su
def admin_partner_audit(guid: str):
    session = get_db()
    p = session.query(ExternalPartner).filter_by(guid=guid).first()
    if p is None:
        return jsonify({'error': 'not_found'}), 404
    entries = (
        session.query(ExternalPartnerAudit)
        .filter_by(partner_guid=guid)
        .order_by(ExternalPartnerAudit.at.desc())
        .limit(200)
        .all()
    )
    return jsonify({'audit': [e.to_dict() for e in entries]}), 200


@partners_bp.route('/api/admin/partners/_meta/catalogue', methods=['GET'])
@require_auth
@require_su
def admin_catalogue():
    """Return the closed-set scope + service catalogues for the admin UI."""
    return jsonify({
        'scopes': SCOPE_CATALOGUE,
        'services': KNOWN_SERVICES,
    }), 200
